<?xml version="1.0" encoding="utf-8"?><Database Name="Lily" Class="LilyModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WIN7--20111029I\TOUFE;Initial Catalog=Lily;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.configSystem" Member="configSystems">
    <Type Name="configSystem">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="value" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="valuestr" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="updatetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updateby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>