#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNotifications.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Lily")]
	public partial class DataLilyModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbank(bank instance);
    partial void Updatebank(bank instance);
    partial void Deletebank(bank instance);
    partial void Insertbot(bot instance);
    partial void Updatebot(bot instance);
    partial void Deletebot(bot instance);
    partial void InsertconfigRobotStrategy(configRobotStrategy instance);
    partial void UpdateconfigRobotStrategy(configRobotStrategy instance);
    partial void DeleteconfigRobotStrategy(configRobotStrategy instance);
    partial void Insertfeedback(feedback instance);
    partial void Updatefeedback(feedback instance);
    partial void Deletefeedback(feedback instance);
    partial void Insertfriend(friend instance);
    partial void Updatefriend(friend instance);
    partial void Deletefriend(friend instance);
    partial void Insertitem(item instance);
    partial void Updateitem(item instance);
    partial void Deleteitem(item instance);
    partial void Insertlogin(login instance);
    partial void Updatelogin(login instance);
    partial void Deletelogin(login instance);
    partial void Insertusermessage(usermessage instance);
    partial void Updateusermessage(usermessage instance);
    partial void Deleteusermessage(usermessage instance);
    partial void Insertusersecond(usersecond instance);
    partial void Updateusersecond(usersecond instance);
    partial void Deleteusersecond(usersecond instance);
    partial void InsertconfigSystem(configSystem instance);
    partial void UpdateconfigSystem(configSystem instance);
    partial void DeleteconfigSystem(configSystem instance);
    partial void Insertuserprop(userprop instance);
    partial void Updateuserprop(userprop instance);
    partial void Deleteuserprop(userprop instance);
    partial void Insertuserpayment(userpayment instance);
    partial void Updateuserpayment(userpayment instance);
    partial void Deleteuserpayment(userpayment instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public DataLilyModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LilyConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataLilyModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLilyModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLilyModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLilyModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bank> banks
		{
			get
			{
				return this.GetTable<bank>();
			}
		}
		
		public System.Data.Linq.Table<bot> bots
		{
			get
			{
				return this.GetTable<bot>();
			}
		}
		
		public System.Data.Linq.Table<configRobotStrategy> configRobotStrategies
		{
			get
			{
				return this.GetTable<configRobotStrategy>();
			}
		}
		
		public System.Data.Linq.Table<feedback> feedbacks
		{
			get
			{
				return this.GetTable<feedback>();
			}
		}
		
		public System.Data.Linq.Table<friend> friends
		{
			get
			{
				return this.GetTable<friend>();
			}
		}
		
		public System.Data.Linq.Table<item> items
		{
			get
			{
				return this.GetTable<item>();
			}
		}
		
		public System.Data.Linq.Table<ReportUserOnline> ReportUserOnlines
		{
			get
			{
				return this.GetTable<ReportUserOnline>();
			}
		}
		
		public System.Data.Linq.Table<login> logins
		{
			get
			{
				return this.GetTable<login>();
			}
		}
		
		public System.Data.Linq.Table<usermessage> usermessages
		{
			get
			{
				return this.GetTable<usermessage>();
			}
		}
		
		public System.Data.Linq.Table<usersecond> userseconds
		{
			get
			{
				return this.GetTable<usersecond>();
			}
		}
		
		public System.Data.Linq.Table<configSystem> configSystems
		{
			get
			{
				return this.GetTable<configSystem>();
			}
		}
		
		public System.Data.Linq.Table<userprop> userprops
		{
			get
			{
				return this.GetTable<userprop>();
			}
		}
		
		public System.Data.Linq.Table<userpayment> userpayments
		{
			get
			{
				return this.GetTable<userpayment>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bank")]
	public partial class bank : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _bankid;
		
		private System.Nullable<long> _bankin;
		
		private System.Nullable<long> _bankout;
		
		private System.Nullable<System.DateTime> _createtime;
		
		private System.Nullable<int> _optype;
		
		private System.Nullable<int> _itemid;
		
		private string _userid;
		
		private System.Nullable<int> _duration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbankidChanging(long value);
    partial void OnbankidChanged();
    partial void OnbankinChanging(System.Nullable<long> value);
    partial void OnbankinChanged();
    partial void OnbankoutChanging(System.Nullable<long> value);
    partial void OnbankoutChanged();
    partial void OncreatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreatetimeChanged();
    partial void OnoptypeChanging(System.Nullable<int> value);
    partial void OnoptypeChanged();
    partial void OnitemidChanging(System.Nullable<int> value);
    partial void OnitemidChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OndurationChanging(System.Nullable<int> value);
    partial void OndurationChanged();
    #endregion
		
		public bank()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long bankid
		{
			get
			{
				return this._bankid;
			}
			set
			{
				if ((this._bankid != value))
				{
					this.OnbankidChanging(value);
					this.SendPropertyChanging();
					this._bankid = value;
					this.SendPropertyChanged("bankid");
					this.OnbankidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankin", DbType="BigInt")]
		public System.Nullable<long> bankin
		{
			get
			{
				return this._bankin;
			}
			set
			{
				if ((this._bankin != value))
				{
					this.OnbankinChanging(value);
					this.SendPropertyChanging();
					this._bankin = value;
					this.SendPropertyChanged("bankin");
					this.OnbankinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankout", DbType="BigInt")]
		public System.Nullable<long> bankout
		{
			get
			{
				return this._bankout;
			}
			set
			{
				if ((this._bankout != value))
				{
					this.OnbankoutChanging(value);
					this.SendPropertyChanging();
					this._bankout = value;
					this.SendPropertyChanged("bankout");
					this.OnbankoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optype", DbType="Int")]
		public System.Nullable<int> optype
		{
			get
			{
				return this._optype;
			}
			set
			{
				if ((this._optype != value))
				{
					this.OnoptypeChanging(value);
					this.SendPropertyChanging();
					this._optype = value;
					this.SendPropertyChanged("optype");
					this.OnoptypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int")]
		public System.Nullable<int> itemid
		{
			get
			{
				return this._itemid;
			}
			set
			{
				if ((this._itemid != value))
				{
					this.OnitemidChanging(value);
					this.SendPropertyChanging();
					this._itemid = value;
					this.SendPropertyChanged("itemid");
					this.OnitemidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Int")]
		public System.Nullable<int> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bots")]
	public partial class bot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _nickname;
		
		private System.Nullable<int> _usertype;
		
		private string _username;
		
		private string _mail;
		
		private string _password;
		
		private string _password2;
		
		private System.Nullable<int> _role;
		
		private System.Nullable<long> _exp;
		
		private System.Nullable<int> _avator;
		
		private System.Nullable<long> _chips;
		
		private System.Nullable<long> _totalgame;
		
		private System.Nullable<int> _wins;
		
		private System.Nullable<decimal> _winningpercentage;
		
		private System.Nullable<long> _maximumwinnote;
		
		private string _besthandtype;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<System.DateTime> _logintime;
		
		private System.Nullable<long> _money;
		
		private System.Nullable<int> _backgroundtype;
		
		private string _roomid;
		
		private System.Nullable<int> _livingroomtype;
		
		private string _userid;
		
		private System.Nullable<int> _besthandvalue;
		
		private System.Nullable<long> _achievements;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnicknameChanging(string value);
    partial void OnnicknameChanged();
    partial void OnusertypeChanging(System.Nullable<int> value);
    partial void OnusertypeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onpassword2Changing(string value);
    partial void Onpassword2Changed();
    partial void OnroleChanging(System.Nullable<int> value);
    partial void OnroleChanged();
    partial void OnexpChanging(System.Nullable<long> value);
    partial void OnexpChanged();
    partial void OnavatorChanging(System.Nullable<int> value);
    partial void OnavatorChanged();
    partial void OnchipsChanging(System.Nullable<long> value);
    partial void OnchipsChanged();
    partial void OntotalgameChanging(System.Nullable<long> value);
    partial void OntotalgameChanged();
    partial void OnwinsChanging(System.Nullable<int> value);
    partial void OnwinsChanged();
    partial void OnwinningpercentageChanging(System.Nullable<decimal> value);
    partial void OnwinningpercentageChanged();
    partial void OnmaximumwinnoteChanging(System.Nullable<long> value);
    partial void OnmaximumwinnoteChanged();
    partial void OnbesthandtypeChanging(string value);
    partial void OnbesthandtypeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnlogintimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlogintimeChanged();
    partial void OnmoneyChanging(System.Nullable<long> value);
    partial void OnmoneyChanged();
    partial void OnbackgroundtypeChanging(System.Nullable<int> value);
    partial void OnbackgroundtypeChanged();
    partial void OnroomidChanging(string value);
    partial void OnroomidChanged();
    partial void OnlivingroomtypeChanging(System.Nullable<int> value);
    partial void OnlivingroomtypeChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnbesthandvalueChanging(System.Nullable<int> value);
    partial void OnbesthandvalueChanged();
    partial void OnachievementsChanging(System.Nullable<long> value);
    partial void OnachievementsChanged();
    #endregion
		
		public bot()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this.OnnicknameChanging(value);
					this.SendPropertyChanging();
					this._nickname = value;
					this.SendPropertyChanged("nickname");
					this.OnnicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="Int")]
		public System.Nullable<int> usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this.OnusertypeChanging(value);
					this.SendPropertyChanging();
					this._usertype = value;
					this.SendPropertyChanged("usertype");
					this.OnusertypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="NVarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password2", DbType="NVarChar(50)")]
		public string password2
		{
			get
			{
				return this._password2;
			}
			set
			{
				if ((this._password2 != value))
				{
					this.Onpassword2Changing(value);
					this.SendPropertyChanging();
					this._password2 = value;
					this.SendPropertyChanged("password2");
					this.Onpassword2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int")]
		public System.Nullable<int> role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exp", DbType="BigInt")]
		public System.Nullable<long> exp
		{
			get
			{
				return this._exp;
			}
			set
			{
				if ((this._exp != value))
				{
					this.OnexpChanging(value);
					this.SendPropertyChanging();
					this._exp = value;
					this.SendPropertyChanged("exp");
					this.OnexpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avator", DbType="Int")]
		public System.Nullable<int> avator
		{
			get
			{
				return this._avator;
			}
			set
			{
				if ((this._avator != value))
				{
					this.OnavatorChanging(value);
					this.SendPropertyChanging();
					this._avator = value;
					this.SendPropertyChanged("avator");
					this.OnavatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chips", DbType="BigInt")]
		public System.Nullable<long> chips
		{
			get
			{
				return this._chips;
			}
			set
			{
				if ((this._chips != value))
				{
					this.OnchipsChanging(value);
					this.SendPropertyChanging();
					this._chips = value;
					this.SendPropertyChanged("chips");
					this.OnchipsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalgame", DbType="BigInt")]
		public System.Nullable<long> totalgame
		{
			get
			{
				return this._totalgame;
			}
			set
			{
				if ((this._totalgame != value))
				{
					this.OntotalgameChanging(value);
					this.SendPropertyChanging();
					this._totalgame = value;
					this.SendPropertyChanged("totalgame");
					this.OntotalgameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wins", DbType="Int")]
		public System.Nullable<int> wins
		{
			get
			{
				return this._wins;
			}
			set
			{
				if ((this._wins != value))
				{
					this.OnwinsChanging(value);
					this.SendPropertyChanging();
					this._wins = value;
					this.SendPropertyChanged("wins");
					this.OnwinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_winningpercentage", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> winningpercentage
		{
			get
			{
				return this._winningpercentage;
			}
			set
			{
				if ((this._winningpercentage != value))
				{
					this.OnwinningpercentageChanging(value);
					this.SendPropertyChanging();
					this._winningpercentage = value;
					this.SendPropertyChanged("winningpercentage");
					this.OnwinningpercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maximumwinnote", DbType="BigInt")]
		public System.Nullable<long> maximumwinnote
		{
			get
			{
				return this._maximumwinnote;
			}
			set
			{
				if ((this._maximumwinnote != value))
				{
					this.OnmaximumwinnoteChanging(value);
					this.SendPropertyChanging();
					this._maximumwinnote = value;
					this.SendPropertyChanged("maximumwinnote");
					this.OnmaximumwinnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_besthandtype", DbType="NVarChar(500)")]
		public string besthandtype
		{
			get
			{
				return this._besthandtype;
			}
			set
			{
				if ((this._besthandtype != value))
				{
					this.OnbesthandtypeChanging(value);
					this.SendPropertyChanging();
					this._besthandtype = value;
					this.SendPropertyChanged("besthandtype");
					this.OnbesthandtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logintime", DbType="DateTime")]
		public System.Nullable<System.DateTime> logintime
		{
			get
			{
				return this._logintime;
			}
			set
			{
				if ((this._logintime != value))
				{
					this.OnlogintimeChanging(value);
					this.SendPropertyChanging();
					this._logintime = value;
					this.SendPropertyChanged("logintime");
					this.OnlogintimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_money", DbType="BigInt")]
		public System.Nullable<long> money
		{
			get
			{
				return this._money;
			}
			set
			{
				if ((this._money != value))
				{
					this.OnmoneyChanging(value);
					this.SendPropertyChanging();
					this._money = value;
					this.SendPropertyChanged("money");
					this.OnmoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_backgroundtype", DbType="Int")]
		public System.Nullable<int> backgroundtype
		{
			get
			{
				return this._backgroundtype;
			}
			set
			{
				if ((this._backgroundtype != value))
				{
					this.OnbackgroundtypeChanging(value);
					this.SendPropertyChanging();
					this._backgroundtype = value;
					this.SendPropertyChanged("backgroundtype");
					this.OnbackgroundtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roomid", DbType="NVarChar(50)")]
		public string roomid
		{
			get
			{
				return this._roomid;
			}
			set
			{
				if ((this._roomid != value))
				{
					this.OnroomidChanging(value);
					this.SendPropertyChanging();
					this._roomid = value;
					this.SendPropertyChanged("roomid");
					this.OnroomidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_livingroomtype", DbType="Int")]
		public System.Nullable<int> livingroomtype
		{
			get
			{
				return this._livingroomtype;
			}
			set
			{
				if ((this._livingroomtype != value))
				{
					this.OnlivingroomtypeChanging(value);
					this.SendPropertyChanging();
					this._livingroomtype = value;
					this.SendPropertyChanged("livingroomtype");
					this.OnlivingroomtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_besthandvalue", DbType="Int")]
		public System.Nullable<int> besthandvalue
		{
			get
			{
				return this._besthandvalue;
			}
			set
			{
				if ((this._besthandvalue != value))
				{
					this.OnbesthandvalueChanging(value);
					this.SendPropertyChanging();
					this._besthandvalue = value;
					this.SendPropertyChanged("besthandvalue");
					this.OnbesthandvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achievements", DbType="BigInt")]
		public System.Nullable<long> achievements
		{
			get
			{
				return this._achievements;
			}
			set
			{
				if ((this._achievements != value))
				{
					this.OnachievementsChanging(value);
					this.SendPropertyChanging();
					this._achievements = value;
					this.SendPropertyChanged("achievements");
					this.OnachievementsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.configRobotStrategy")]
	public partial class configRobotStrategy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _strategyid;
		
		private string _strategy;
		
		private int _typeround;
		
		private int _foldratio;
		
		private int _callratio;
		
		private System.Nullable<int> _delaymin;
		
		private System.Nullable<int> _delaymax;
		
		private System.Nullable<int> _rasiea;
		
		private System.Nullable<int> _rasieb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstrategyidChanging(int value);
    partial void OnstrategyidChanged();
    partial void OnstrategyChanging(string value);
    partial void OnstrategyChanged();
    partial void OntyperoundChanging(int value);
    partial void OntyperoundChanged();
    partial void OnfoldratioChanging(int value);
    partial void OnfoldratioChanged();
    partial void OncallratioChanging(int value);
    partial void OncallratioChanged();
    partial void OndelayminChanging(System.Nullable<int> value);
    partial void OndelayminChanged();
    partial void OndelaymaxChanging(System.Nullable<int> value);
    partial void OndelaymaxChanged();
    partial void OnrasieaChanging(System.Nullable<int> value);
    partial void OnrasieaChanged();
    partial void OnrasiebChanging(System.Nullable<int> value);
    partial void OnrasiebChanged();
    #endregion
		
		public configRobotStrategy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strategyid", DbType="Int NOT NULL")]
		public int strategyid
		{
			get
			{
				return this._strategyid;
			}
			set
			{
				if ((this._strategyid != value))
				{
					this.OnstrategyidChanging(value);
					this.SendPropertyChanging();
					this._strategyid = value;
					this.SendPropertyChanged("strategyid");
					this.OnstrategyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strategy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string strategy
		{
			get
			{
				return this._strategy;
			}
			set
			{
				if ((this._strategy != value))
				{
					this.OnstrategyChanging(value);
					this.SendPropertyChanging();
					this._strategy = value;
					this.SendPropertyChanged("strategy");
					this.OnstrategyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeround", DbType="Int NOT NULL")]
		public int typeround
		{
			get
			{
				return this._typeround;
			}
			set
			{
				if ((this._typeround != value))
				{
					this.OntyperoundChanging(value);
					this.SendPropertyChanging();
					this._typeround = value;
					this.SendPropertyChanged("typeround");
					this.OntyperoundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foldratio", DbType="Int NOT NULL")]
		public int foldratio
		{
			get
			{
				return this._foldratio;
			}
			set
			{
				if ((this._foldratio != value))
				{
					this.OnfoldratioChanging(value);
					this.SendPropertyChanging();
					this._foldratio = value;
					this.SendPropertyChanged("foldratio");
					this.OnfoldratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_callratio", DbType="Int NOT NULL")]
		public int callratio
		{
			get
			{
				return this._callratio;
			}
			set
			{
				if ((this._callratio != value))
				{
					this.OncallratioChanging(value);
					this.SendPropertyChanging();
					this._callratio = value;
					this.SendPropertyChanged("callratio");
					this.OncallratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delaymin", DbType="Int")]
		public System.Nullable<int> delaymin
		{
			get
			{
				return this._delaymin;
			}
			set
			{
				if ((this._delaymin != value))
				{
					this.OndelayminChanging(value);
					this.SendPropertyChanging();
					this._delaymin = value;
					this.SendPropertyChanged("delaymin");
					this.OndelayminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delaymax", DbType="Int")]
		public System.Nullable<int> delaymax
		{
			get
			{
				return this._delaymax;
			}
			set
			{
				if ((this._delaymax != value))
				{
					this.OndelaymaxChanging(value);
					this.SendPropertyChanging();
					this._delaymax = value;
					this.SendPropertyChanged("delaymax");
					this.OndelaymaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rasiea", DbType="Int")]
		public System.Nullable<int> rasiea
		{
			get
			{
				return this._rasiea;
			}
			set
			{
				if ((this._rasiea != value))
				{
					this.OnrasieaChanging(value);
					this.SendPropertyChanging();
					this._rasiea = value;
					this.SendPropertyChanged("rasiea");
					this.OnrasieaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rasieb", DbType="Int")]
		public System.Nullable<int> rasieb
		{
			get
			{
				return this._rasieb;
			}
			set
			{
				if ((this._rasieb != value))
				{
					this.OnrasiebChanging(value);
					this.SendPropertyChanging();
					this._rasieb = value;
					this.SendPropertyChanged("rasieb");
					this.OnrasiebChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.feedback")]
	public partial class feedback : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _userid;
		
		private string _content;
		
		private System.Nullable<System.DateTime> _time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OntimeChanging(System.Nullable<System.DateTime> value);
    partial void OntimeChanged();
    #endregion
		
		public feedback()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.friend")]
	public partial class friend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _userA;
		
		private string _userB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnuserAChanging(string value);
    partial void OnuserAChanged();
    partial void OnuserBChanging(string value);
    partial void OnuserBChanged();
    #endregion
		
		public friend()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userA
		{
			get
			{
				return this._userA;
			}
			set
			{
				if ((this._userA != value))
				{
					this.OnuserAChanging(value);
					this.SendPropertyChanging();
					this._userA = value;
					this.SendPropertyChanged("userA");
					this.OnuserAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userB
		{
			get
			{
				return this._userB;
			}
			set
			{
				if ((this._userB != value))
				{
					this.OnuserBChanging(value);
					this.SendPropertyChanging();
					this._userB = value;
					this.SendPropertyChanged("userB");
					this.OnuserBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.item")]
	public partial class item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _userid;
		
		private int _type;
		
		private bool _used;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void OnusedChanging(bool value);
    partial void OnusedChanged();
    #endregion
		
		public item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_used", DbType="Bit NOT NULL")]
		public bool used
		{
			get
			{
				return this._used;
			}
			set
			{
				if ((this._used != value))
				{
					this.OnusedChanging(value);
					this.SendPropertyChanging();
					this._used = value;
					this.SendPropertyChanged("used");
					this.OnusedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportUserOnline")]
	public partial class ReportUserOnline
	{
		
		private System.DateTime _reportDate;
		
		private string _reportContent;
		
		private System.Nullable<System.DateTime> _updatetime;
		
		public ReportUserOnline()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reportDate", DbType="Date NOT NULL")]
		public System.DateTime reportDate
		{
			get
			{
				return this._reportDate;
			}
			set
			{
				if ((this._reportDate != value))
				{
					this._reportDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reportContent", DbType="NVarChar(500)")]
		public string reportContent
		{
			get
			{
				return this._reportContent;
			}
			set
			{
				if ((this._reportContent != value))
				{
					this._reportContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatetime
		{
			get
			{
				return this._updatetime;
			}
			set
			{
				if ((this._updatetime != value))
				{
					this._updatetime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.login")]
	public partial class login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _useridstr;
		
		private System.Nullable<System.DateTime> _logintime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnuseridstrChanging(string value);
    partial void OnuseridstrChanged();
    partial void OnlogintimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlogintimeChanged();
    #endregion
		
		public login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_useridstr", DbType="VarChar(50)")]
		public string useridstr
		{
			get
			{
				return this._useridstr;
			}
			set
			{
				if ((this._useridstr != value))
				{
					this.OnuseridstrChanging(value);
					this.SendPropertyChanging();
					this._useridstr = value;
					this.SendPropertyChanged("useridstr");
					this.OnuseridstrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logintime", DbType="DateTime")]
		public System.Nullable<System.DateTime> logintime
		{
			get
			{
				return this._logintime;
			}
			set
			{
				if ((this._logintime != value))
				{
					this.OnlogintimeChanging(value);
					this.SendPropertyChanging();
					this._logintime = value;
					this.SendPropertyChanged("logintime");
					this.OnlogintimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usermessage")]
	public partial class usermessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _sender;
		
		private string _receiver;
		
		private byte _messagetype;
		
		private string _content;
		
		private System.Nullable<System.DateTime> _time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnsenderChanging(string value);
    partial void OnsenderChanged();
    partial void OnreceiverChanging(string value);
    partial void OnreceiverChanged();
    partial void OnmessagetypeChanging(byte value);
    partial void OnmessagetypeChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OntimeChanging(System.Nullable<System.DateTime> value);
    partial void OntimeChanged();
    #endregion
		
		public usermessage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sender", DbType="NVarChar(50)")]
		public string sender
		{
			get
			{
				return this._sender;
			}
			set
			{
				if ((this._sender != value))
				{
					this.OnsenderChanging(value);
					this.SendPropertyChanging();
					this._sender = value;
					this.SendPropertyChanged("sender");
					this.OnsenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receiver", DbType="NVarChar(50)")]
		public string receiver
		{
			get
			{
				return this._receiver;
			}
			set
			{
				if ((this._receiver != value))
				{
					this.OnreceiverChanging(value);
					this.SendPropertyChanging();
					this._receiver = value;
					this.SendPropertyChanged("receiver");
					this.OnreceiverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_messagetype", DbType="TinyInt NOT NULL")]
		public byte messagetype
		{
			get
			{
				return this._messagetype;
			}
			set
			{
				if ((this._messagetype != value))
				{
					this.OnmessagetypeChanging(value);
					this.SendPropertyChanging();
					this._messagetype = value;
					this.SendPropertyChanged("messagetype");
					this.OnmessagetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usersecond")]
	public partial class usersecond : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nickname;
		
		private string _userIdStr;
		
		private System.Nullable<long> _overallPoints;
		
		private System.Nullable<System.DateTime> _registertime;
		
		private System.Nullable<int> _usertype;
		
		private System.Nullable<int> _sex;
		
		private System.Nullable<System.DateTime> _upgradetime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnicknameChanging(string value);
    partial void OnnicknameChanged();
    partial void OnuserIdStrChanging(string value);
    partial void OnuserIdStrChanged();
    partial void OnoverallPointsChanging(System.Nullable<long> value);
    partial void OnoverallPointsChanged();
    partial void OnregistertimeChanging(System.Nullable<System.DateTime> value);
    partial void OnregistertimeChanged();
    partial void OnusertypeChanging(System.Nullable<int> value);
    partial void OnusertypeChanged();
    partial void OnsexChanging(System.Nullable<int> value);
    partial void OnsexChanged();
    partial void OnupgradetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupgradetimeChanged();
    #endregion
		
		public usersecond()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="VarChar(45)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this.OnnicknameChanging(value);
					this.SendPropertyChanging();
					this._nickname = value;
					this.SendPropertyChanged("nickname");
					this.OnnicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdStr", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userIdStr
		{
			get
			{
				return this._userIdStr;
			}
			set
			{
				if ((this._userIdStr != value))
				{
					this.OnuserIdStrChanging(value);
					this.SendPropertyChanging();
					this._userIdStr = value;
					this.SendPropertyChanged("userIdStr");
					this.OnuserIdStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overallPoints", DbType="BigInt")]
		public System.Nullable<long> overallPoints
		{
			get
			{
				return this._overallPoints;
			}
			set
			{
				if ((this._overallPoints != value))
				{
					this.OnoverallPointsChanging(value);
					this.SendPropertyChanging();
					this._overallPoints = value;
					this.SendPropertyChanged("overallPoints");
					this.OnoverallPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registertime", DbType="DateTime")]
		public System.Nullable<System.DateTime> registertime
		{
			get
			{
				return this._registertime;
			}
			set
			{
				if ((this._registertime != value))
				{
					this.OnregistertimeChanging(value);
					this.SendPropertyChanging();
					this._registertime = value;
					this.SendPropertyChanged("registertime");
					this.OnregistertimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="Int")]
		public System.Nullable<int> usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this.OnusertypeChanging(value);
					this.SendPropertyChanging();
					this._usertype = value;
					this.SendPropertyChanged("usertype");
					this.OnusertypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="Int")]
		public System.Nullable<int> sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upgradetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> upgradetime
		{
			get
			{
				return this._upgradetime;
			}
			set
			{
				if ((this._upgradetime != value))
				{
					this.OnupgradetimeChanging(value);
					this.SendPropertyChanging();
					this._upgradetime = value;
					this.SendPropertyChanged("upgradetime");
					this.OnupgradetimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.configSystem")]
	public partial class configSystem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _description;
		
		private decimal _value;
		
		private string _valuestr;
		
		private System.Nullable<System.DateTime> _updatetime;
		
		private string _updateby;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnvalueChanging(decimal value);
    partial void OnvalueChanged();
    partial void OnvaluestrChanging(string value);
    partial void OnvaluestrChanged();
    partial void OnupdatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatetimeChanged();
    partial void OnupdatebyChanging(string value);
    partial void OnupdatebyChanged();
    #endregion
		
		public configSystem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Decimal(18,3) NOT NULL")]
		public decimal value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valuestr", DbType="NVarChar(500)")]
		public string valuestr
		{
			get
			{
				return this._valuestr;
			}
			set
			{
				if ((this._valuestr != value))
				{
					this.OnvaluestrChanging(value);
					this.SendPropertyChanging();
					this._valuestr = value;
					this.SendPropertyChanged("valuestr");
					this.OnvaluestrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatetime
		{
			get
			{
				return this._updatetime;
			}
			set
			{
				if ((this._updatetime != value))
				{
					this.OnupdatetimeChanging(value);
					this.SendPropertyChanging();
					this._updatetime = value;
					this.SendPropertyChanged("updatetime");
					this.OnupdatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateby", DbType="NVarChar(50)")]
		public string updateby
		{
			get
			{
				return this._updateby;
			}
			set
			{
				if ((this._updateby != value))
				{
					this.OnupdatebyChanging(value);
					this.SendPropertyChanging();
					this._updateby = value;
					this.SendPropertyChanged("updateby");
					this.OnupdatebyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userprops")]
	public partial class userprop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ItemType;
		
		private int _ItemId;
		
		private string _ItemName;
		
		private int _Duration;
		
		private string _UserId;
		
		private System.DateTime _PurchaseDate;
		
		private int _Status;
		
		private System.Nullable<System.DateTime> _UseDate;
		
		private System.Nullable<System.DateTime> _FailureDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemTypeChanging(int value);
    partial void OnItemTypeChanged();
    partial void OnItemIdChanging(int value);
    partial void OnItemIdChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnDurationChanging(int value);
    partial void OnDurationChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnPurchaseDateChanging(System.DateTime value);
    partial void OnPurchaseDateChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnUseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUseDateChanged();
    partial void OnFailureDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFailureDateChanged();
    #endregion
		
		public userprop()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemType", DbType="Int NOT NULL")]
		public int ItemType
		{
			get
			{
				return this._ItemType;
			}
			set
			{
				if ((this._ItemType != value))
				{
					this.OnItemTypeChanging(value);
					this.SendPropertyChanging();
					this._ItemType = value;
					this.SendPropertyChanged("ItemType");
					this.OnItemTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int NOT NULL")]
		public int ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(50)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this.OnItemNameChanging(value);
					this.SendPropertyChanging();
					this._ItemName = value;
					this.SendPropertyChanged("ItemName");
					this.OnItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="Int NOT NULL")]
		public int Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseDate", DbType="DateTime NOT NULL")]
		public System.DateTime PurchaseDate
		{
			get
			{
				return this._PurchaseDate;
			}
			set
			{
				if ((this._PurchaseDate != value))
				{
					this.OnPurchaseDateChanging(value);
					this.SendPropertyChanging();
					this._PurchaseDate = value;
					this.SendPropertyChanged("PurchaseDate");
					this.OnPurchaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UseDate
		{
			get
			{
				return this._UseDate;
			}
			set
			{
				if ((this._UseDate != value))
				{
					this.OnUseDateChanging(value);
					this.SendPropertyChanging();
					this._UseDate = value;
					this.SendPropertyChanged("UseDate");
					this.OnUseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailureDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FailureDate
		{
			get
			{
				return this._FailureDate;
			}
			set
			{
				if ((this._FailureDate != value))
				{
					this.OnFailureDateChanging(value);
					this.SendPropertyChanging();
					this._FailureDate = value;
					this.SendPropertyChanged("FailureDate");
					this.OnFailureDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userpayment")]
	public partial class userpayment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<long> _itemid;
		
		private string _note;
		
		private System.Nullable<decimal> _money;
		
		private string _userid;
		
		private System.Nullable<int> _payway;
		
		private string _alipaynote;
		
		private string _channelId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntimeChanging(System.Nullable<System.DateTime> value);
    partial void OntimeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OnitemidChanging(System.Nullable<long> value);
    partial void OnitemidChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OnmoneyChanging(System.Nullable<decimal> value);
    partial void OnmoneyChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnpaywayChanging(System.Nullable<int> value);
    partial void OnpaywayChanged();
    partial void OnalipaynoteChanging(string value);
    partial void OnalipaynoteChanged();
    partial void OnchannelIdChanging(string value);
    partial void OnchannelIdChanged();
    #endregion
		
		public userpayment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="BigInt")]
		public System.Nullable<long> itemid
		{
			get
			{
				return this._itemid;
			}
			set
			{
				if ((this._itemid != value))
				{
					this.OnitemidChanging(value);
					this.SendPropertyChanging();
					this._itemid = value;
					this.SendPropertyChanged("itemid");
					this.OnitemidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_money", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> money
		{
			get
			{
				return this._money;
			}
			set
			{
				if ((this._money != value))
				{
					this.OnmoneyChanging(value);
					this.SendPropertyChanging();
					this._money = value;
					this.SendPropertyChanged("money");
					this.OnmoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payway", DbType="Int")]
		public System.Nullable<int> payway
		{
			get
			{
				return this._payway;
			}
			set
			{
				if ((this._payway != value))
				{
					this.OnpaywayChanging(value);
					this.SendPropertyChanging();
					this._payway = value;
					this.SendPropertyChanged("payway");
					this.OnpaywayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alipaynote", DbType="VarChar(50)")]
		public string alipaynote
		{
			get
			{
				return this._alipaynote;
			}
			set
			{
				if ((this._alipaynote != value))
				{
					this.OnalipaynoteChanging(value);
					this.SendPropertyChanging();
					this._alipaynote = value;
					this.SendPropertyChanged("alipaynote");
					this.OnalipaynoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channelId", DbType="NVarChar(50)")]
		public string channelId
		{
			get
			{
				return this._channelId;
			}
			set
			{
				if ((this._channelId != value))
				{
					this.OnchannelIdChanging(value);
					this.SendPropertyChanging();
					this._channelId = value;
					this.SendPropertyChanged("channelId");
					this.OnchannelIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _nickname;
		
		private System.Nullable<int> _usertype;
		
		private string _username;
		
		private string _mail;
		
		private string _password;
		
		private string _password2;
		
		private System.Nullable<int> _role;
		
		private System.Nullable<long> _exp;
		
		private System.Nullable<int> _avator;
		
		private System.Nullable<long> _chips;
		
		private System.Nullable<long> _totalgame;
		
		private System.Nullable<int> _wins;
		
		private System.Nullable<decimal> _winningpercentage;
		
		private System.Nullable<long> _maximumwinnote;
		
		private string _besthandtype;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<System.DateTime> _logintime;
		
		private System.Nullable<long> _money;
		
		private System.Nullable<int> _backgroundtype;
		
		private string _roomid;
		
		private int _livingroomtype;
		
		private string _userid;
		
		private int _ownroomtypes;
		
		private System.Nullable<int> _besthandvalue;
		
		private System.Nullable<int> _devicetype;
		
		private string _devicetoken;
		
		private System.Nullable<long> _achievements;
		
		private System.Nullable<bool> _hasbuy;
		
		private System.Nullable<bool> _systempn;
		
		private System.Nullable<bool> _friendpn;
		
		private string _awards;
		
		private System.Nullable<decimal> _awardsadd;
		
		private System.Nullable<int> _expadd;
		
		private System.Nullable<decimal> _winadd;
		
		private string _channelid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnicknameChanging(string value);
    partial void OnnicknameChanged();
    partial void OnusertypeChanging(System.Nullable<int> value);
    partial void OnusertypeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onpassword2Changing(string value);
    partial void Onpassword2Changed();
    partial void OnroleChanging(System.Nullable<int> value);
    partial void OnroleChanged();
    partial void OnexpChanging(System.Nullable<long> value);
    partial void OnexpChanged();
    partial void OnavatorChanging(System.Nullable<int> value);
    partial void OnavatorChanged();
    partial void OnchipsChanging(System.Nullable<long> value);
    partial void OnchipsChanged();
    partial void OntotalgameChanging(System.Nullable<long> value);
    partial void OntotalgameChanged();
    partial void OnwinsChanging(System.Nullable<int> value);
    partial void OnwinsChanged();
    partial void OnwinningpercentageChanging(System.Nullable<decimal> value);
    partial void OnwinningpercentageChanged();
    partial void OnmaximumwinnoteChanging(System.Nullable<long> value);
    partial void OnmaximumwinnoteChanged();
    partial void OnbesthandtypeChanging(string value);
    partial void OnbesthandtypeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnlogintimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlogintimeChanged();
    partial void OnmoneyChanging(System.Nullable<long> value);
    partial void OnmoneyChanged();
    partial void OnbackgroundtypeChanging(System.Nullable<int> value);
    partial void OnbackgroundtypeChanged();
    partial void OnroomidChanging(string value);
    partial void OnroomidChanged();
    partial void OnlivingroomtypeChanging(int value);
    partial void OnlivingroomtypeChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnownroomtypesChanging(int value);
    partial void OnownroomtypesChanged();
    partial void OnbesthandvalueChanging(System.Nullable<int> value);
    partial void OnbesthandvalueChanged();
    partial void OndevicetypeChanging(System.Nullable<int> value);
    partial void OndevicetypeChanged();
    partial void OndevicetokenChanging(string value);
    partial void OndevicetokenChanged();
    partial void OnachievementsChanging(System.Nullable<long> value);
    partial void OnachievementsChanged();
    partial void OnhasbuyChanging(System.Nullable<bool> value);
    partial void OnhasbuyChanged();
    partial void OnsystempnChanging(System.Nullable<bool> value);
    partial void OnsystempnChanged();
    partial void OnfriendpnChanging(System.Nullable<bool> value);
    partial void OnfriendpnChanged();
    partial void OnawardsChanging(string value);
    partial void OnawardsChanged();
    partial void OnawardsaddChanging(System.Nullable<decimal> value);
    partial void OnawardsaddChanged();
    partial void OnexpaddChanging(System.Nullable<int> value);
    partial void OnexpaddChanged();
    partial void OnwinaddChanging(System.Nullable<decimal> value);
    partial void OnwinaddChanged();
    partial void OnchannelidChanging(string value);
    partial void OnchannelidChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this.OnnicknameChanging(value);
					this.SendPropertyChanging();
					this._nickname = value;
					this.SendPropertyChanged("nickname");
					this.OnnicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="Int")]
		public System.Nullable<int> usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this.OnusertypeChanging(value);
					this.SendPropertyChanging();
					this._usertype = value;
					this.SendPropertyChanged("usertype");
					this.OnusertypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="NVarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password2", DbType="NVarChar(50)")]
		public string password2
		{
			get
			{
				return this._password2;
			}
			set
			{
				if ((this._password2 != value))
				{
					this.Onpassword2Changing(value);
					this.SendPropertyChanging();
					this._password2 = value;
					this.SendPropertyChanged("password2");
					this.Onpassword2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int")]
		public System.Nullable<int> role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exp", DbType="BigInt")]
		public System.Nullable<long> exp
		{
			get
			{
				return this._exp;
			}
			set
			{
				if ((this._exp != value))
				{
					this.OnexpChanging(value);
					this.SendPropertyChanging();
					this._exp = value;
					this.SendPropertyChanged("exp");
					this.OnexpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avator", DbType="Int")]
		public System.Nullable<int> avator
		{
			get
			{
				return this._avator;
			}
			set
			{
				if ((this._avator != value))
				{
					this.OnavatorChanging(value);
					this.SendPropertyChanging();
					this._avator = value;
					this.SendPropertyChanged("avator");
					this.OnavatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chips", DbType="BigInt")]
		public System.Nullable<long> chips
		{
			get
			{
				return this._chips;
			}
			set
			{
				if ((this._chips != value))
				{
					this.OnchipsChanging(value);
					this.SendPropertyChanging();
					this._chips = value;
					this.SendPropertyChanged("chips");
					this.OnchipsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalgame", DbType="BigInt")]
		public System.Nullable<long> totalgame
		{
			get
			{
				return this._totalgame;
			}
			set
			{
				if ((this._totalgame != value))
				{
					this.OntotalgameChanging(value);
					this.SendPropertyChanging();
					this._totalgame = value;
					this.SendPropertyChanged("totalgame");
					this.OntotalgameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wins", DbType="Int")]
		public System.Nullable<int> wins
		{
			get
			{
				return this._wins;
			}
			set
			{
				if ((this._wins != value))
				{
					this.OnwinsChanging(value);
					this.SendPropertyChanging();
					this._wins = value;
					this.SendPropertyChanged("wins");
					this.OnwinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_winningpercentage", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> winningpercentage
		{
			get
			{
				return this._winningpercentage;
			}
			set
			{
				if ((this._winningpercentage != value))
				{
					this.OnwinningpercentageChanging(value);
					this.SendPropertyChanging();
					this._winningpercentage = value;
					this.SendPropertyChanged("winningpercentage");
					this.OnwinningpercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maximumwinnote", DbType="BigInt")]
		public System.Nullable<long> maximumwinnote
		{
			get
			{
				return this._maximumwinnote;
			}
			set
			{
				if ((this._maximumwinnote != value))
				{
					this.OnmaximumwinnoteChanging(value);
					this.SendPropertyChanging();
					this._maximumwinnote = value;
					this.SendPropertyChanged("maximumwinnote");
					this.OnmaximumwinnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_besthandtype", DbType="NVarChar(500)")]
		public string besthandtype
		{
			get
			{
				return this._besthandtype;
			}
			set
			{
				if ((this._besthandtype != value))
				{
					this.OnbesthandtypeChanging(value);
					this.SendPropertyChanging();
					this._besthandtype = value;
					this.SendPropertyChanged("besthandtype");
					this.OnbesthandtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logintime", DbType="DateTime")]
		public System.Nullable<System.DateTime> logintime
		{
			get
			{
				return this._logintime;
			}
			set
			{
				if ((this._logintime != value))
				{
					this.OnlogintimeChanging(value);
					this.SendPropertyChanging();
					this._logintime = value;
					this.SendPropertyChanged("logintime");
					this.OnlogintimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_money", DbType="BigInt")]
		public System.Nullable<long> money
		{
			get
			{
				return this._money;
			}
			set
			{
				if ((this._money != value))
				{
					this.OnmoneyChanging(value);
					this.SendPropertyChanging();
					this._money = value;
					this.SendPropertyChanged("money");
					this.OnmoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_backgroundtype", DbType="Int")]
		public System.Nullable<int> backgroundtype
		{
			get
			{
				return this._backgroundtype;
			}
			set
			{
				if ((this._backgroundtype != value))
				{
					this.OnbackgroundtypeChanging(value);
					this.SendPropertyChanging();
					this._backgroundtype = value;
					this.SendPropertyChanged("backgroundtype");
					this.OnbackgroundtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roomid", DbType="NVarChar(50)")]
		public string roomid
		{
			get
			{
				return this._roomid;
			}
			set
			{
				if ((this._roomid != value))
				{
					this.OnroomidChanging(value);
					this.SendPropertyChanging();
					this._roomid = value;
					this.SendPropertyChanged("roomid");
					this.OnroomidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_livingroomtype", DbType="Int NOT NULL")]
		public int livingroomtype
		{
			get
			{
				return this._livingroomtype;
			}
			set
			{
				if ((this._livingroomtype != value))
				{
					this.OnlivingroomtypeChanging(value);
					this.SendPropertyChanging();
					this._livingroomtype = value;
					this.SendPropertyChanged("livingroomtype");
					this.OnlivingroomtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownroomtypes", DbType="Int NOT NULL")]
		public int ownroomtypes
		{
			get
			{
				return this._ownroomtypes;
			}
			set
			{
				if ((this._ownroomtypes != value))
				{
					this.OnownroomtypesChanging(value);
					this.SendPropertyChanging();
					this._ownroomtypes = value;
					this.SendPropertyChanged("ownroomtypes");
					this.OnownroomtypesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_besthandvalue", DbType="Int")]
		public System.Nullable<int> besthandvalue
		{
			get
			{
				return this._besthandvalue;
			}
			set
			{
				if ((this._besthandvalue != value))
				{
					this.OnbesthandvalueChanging(value);
					this.SendPropertyChanging();
					this._besthandvalue = value;
					this.SendPropertyChanged("besthandvalue");
					this.OnbesthandvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicetype", DbType="Int")]
		public System.Nullable<int> devicetype
		{
			get
			{
				return this._devicetype;
			}
			set
			{
				if ((this._devicetype != value))
				{
					this.OndevicetypeChanging(value);
					this.SendPropertyChanging();
					this._devicetype = value;
					this.SendPropertyChanged("devicetype");
					this.OndevicetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicetoken", DbType="NVarChar(200)")]
		public string devicetoken
		{
			get
			{
				return this._devicetoken;
			}
			set
			{
				if ((this._devicetoken != value))
				{
					this.OndevicetokenChanging(value);
					this.SendPropertyChanging();
					this._devicetoken = value;
					this.SendPropertyChanged("devicetoken");
					this.OndevicetokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achievements", DbType="BigInt")]
		public System.Nullable<long> achievements
		{
			get
			{
				return this._achievements;
			}
			set
			{
				if ((this._achievements != value))
				{
					this.OnachievementsChanging(value);
					this.SendPropertyChanging();
					this._achievements = value;
					this.SendPropertyChanged("achievements");
					this.OnachievementsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasbuy", DbType="Bit")]
		public System.Nullable<bool> hasbuy
		{
			get
			{
				return this._hasbuy;
			}
			set
			{
				if ((this._hasbuy != value))
				{
					this.OnhasbuyChanging(value);
					this.SendPropertyChanging();
					this._hasbuy = value;
					this.SendPropertyChanged("hasbuy");
					this.OnhasbuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_systempn", DbType="Bit")]
		public System.Nullable<bool> systempn
		{
			get
			{
				return this._systempn;
			}
			set
			{
				if ((this._systempn != value))
				{
					this.OnsystempnChanging(value);
					this.SendPropertyChanging();
					this._systempn = value;
					this.SendPropertyChanged("systempn");
					this.OnsystempnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendpn", DbType="Bit")]
		public System.Nullable<bool> friendpn
		{
			get
			{
				return this._friendpn;
			}
			set
			{
				if ((this._friendpn != value))
				{
					this.OnfriendpnChanging(value);
					this.SendPropertyChanging();
					this._friendpn = value;
					this.SendPropertyChanged("friendpn");
					this.OnfriendpnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_awards", DbType="VarChar(100)")]
		public string awards
		{
			get
			{
				return this._awards;
			}
			set
			{
				if ((this._awards != value))
				{
					this.OnawardsChanging(value);
					this.SendPropertyChanging();
					this._awards = value;
					this.SendPropertyChanged("awards");
					this.OnawardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_awardsadd", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> awardsadd
		{
			get
			{
				return this._awardsadd;
			}
			set
			{
				if ((this._awardsadd != value))
				{
					this.OnawardsaddChanging(value);
					this.SendPropertyChanging();
					this._awardsadd = value;
					this.SendPropertyChanged("awardsadd");
					this.OnawardsaddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expadd", DbType="Int")]
		public System.Nullable<int> expadd
		{
			get
			{
				return this._expadd;
			}
			set
			{
				if ((this._expadd != value))
				{
					this.OnexpaddChanging(value);
					this.SendPropertyChanging();
					this._expadd = value;
					this.SendPropertyChanged("expadd");
					this.OnexpaddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_winadd", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> winadd
		{
			get
			{
				return this._winadd;
			}
			set
			{
				if ((this._winadd != value))
				{
					this.OnwinaddChanging(value);
					this.SendPropertyChanging();
					this._winadd = value;
					this.SendPropertyChanged("winadd");
					this.OnwinaddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channelid", DbType="NVarChar(50)")]
		public string channelid
		{
			get
			{
				return this._channelid;
			}
			set
			{
				if ((this._channelid != value))
				{
					this.OnchannelidChanging(value);
					this.SendPropertyChanging();
					this._channelid = value;
					this.SendPropertyChanged("channelid");
					this.OnchannelidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
